:PROPERTIES:
:ID:       8C7E9E52-9220-4A7B-B0E6-54F960E17CA8
:END:
#+TITLE: Interview preparation: V

#+BEGIN_ABSTRACT
This note tracks my experience of helping my friend V on their preparation for coding interviews.  It has been awhile since last time that V solved a coding challenge, and as any other skill if you don't practice it you lose it.  I have two purposes for this note: track V's evolution through the preparation and use it as a place to formalize my method on how to improve in problem solving.  By method, I mean the result of experiments that I did on myself (2022) after getting back from many years without practice to coding competitions.  This is a living document and you might visit it multiple times if you want to follow V's journey.
#+END_ABSTRACT
#+TOC: headlines 2

* Coding Interviews

To best define the preparation required for coding interviews, let's compare (coding) interview problems with problems that we usually see on Computer Science's courses.  They require application of knowledge in Data Structure, Algorithms on Graphs and ad-hoc strategies (e.g. Dynamic Programming, Line-Sweeping, Sliding-Window etc).  They differ in two aspects: time to solve and difficult.  You have many days to solve an assignment exercise, but only have 15-20 minutes to solve an interview problem.  Due this difference in time to solve, you can expect interview problems to be easier than most of the assignments that you've done on University.

Due the wide range of topics covered and restriction in time, interview problems are more like final exam's questions on Data Structure and Algorithms courses than assignments.  But there is an important difference.  While you do your exam alone and in silence, you have to verbalize your thoughts while solving the interview problem.  It is definitely an extra challenge, but also an opportunity to engage with the interviewer in case you don't see the solution right away.

The structure and requirements of coding interviews ask for two distinct preparations: studying and performing.  You have to quickly find the solution for the problem using the right data structure, algorithm or technique.  While doing so, you have to perform the interview routine: come up with a solution, explain your thought process and code it in a clear and concise way.  /Learning/ does not need to be time-bounded, since some concepts require time to sink in.  But /performing/ should follow as close as possible a real interview with time constraints and feedback.

A popular way to study is using a curated lists like [[https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions][Blind 75]].  Such lists cover majority of topics that you see in an interview.  These problems cover specific data structures, algorithms and techniques that work as building blocks for your future solutions.  While these lists are a good start, you might have more success if you discover the kind of problems that your target company asks.  It is not that a company uses only one type of questions, but their interviewers might converge to a sub-set of topics due internal culture or type of business.  Since during the interview you do not know the problem's type, it is wise to also study without using hints like Array, Graphs, DP etc.  To play safe, practice as many topics and problems that you can.


* Spaced-repetition

Spaced-repetition is a study-technique commonly used to memorization of factual information.  It uses flashcard as way to store and review content.  A flashcard has two sides: front and back.  A question or prompt goes in the front of the card, and the information to memorize goes on the back.  For example, you have a picture of someone in the front of the card and their name on the back.  The technique uses the [[https://en.wikipedia.org/wiki/Spacing_effect][spacing effect]] to encode information in the long-term memory by spacing the study sessions, and it is known to have better results than [[https://en.wikipedia.org/wiki/Cramming_(education)][cramming]] (repeat many times in a single session).  Difficult cards appear more often while easier ones are less frequent.  [[https://ankiweb.net/][Anki]] is a well-know and flexible program to manage cards.

How spaced-repetition can be applied to problem solving.  While this technique has proven to be efficient when memorizing facts, it still unclear its impact on other types of study.  My bet is that we can use spaced-repetition to prepare for interviews in the following way.  After you solve a problem, you create a card that contains the problem statement (or simplify a link to the problem) and put on the back the steps that you should take to solve the problem.  By steps, I mean the observation that you found crucial to solve the problem.  Building blocks that you used to solve the problem in the correct order.  For example:

- Constraints require a logarithmic solution.
- One element of the array with its neighbors is enough to decide which side of the array lays the answer.
- Use a Binary-search for find the answer.


* Method
:PROPERTIES:
:ID:       B38C0682-EB89-466F-9645-E89A055D3D99
:END:

An studying session is divided in two parts: solving new problems and reviewing old problems.

*For new problems*, you pick one or two problems per day and spend as much time you need to solve them.  If you solved the problem, follow the instructions on [[id:65FBC7A2-7F72-47E8-9462-58E35974DE1D][Creating a new card]].  Otherwise, give at least one day to try again.  On the second day, you can check a solution to the problem.  The goal is to understand the solution and find the gaps on your knowledge.  There is a data structure that you are not familiar, a particular technique or idea that makes the problem dead easy to solve.  After you learned how to solve the problem (congrats!), [[id:65FBC7A2-7F72-47E8-9462-58E35974DE1D][create a card]] for it and move on.

*For old problems*, you open Anki and practice each available card (/new/ and /for review/).  Avoid reviewing cards using "Easy" button since they schedule a new review for too far way.  Use the "Good" button if you solved the problem without any issues: recalled the steps to solve it and passed the problem on the first try.  The "Hard" button should be used if you had difficult on recalling the steps to solve the problem or when coding it.  Reserve the "Again" button for when you couldn't solve the problem at all.  Be emotionally ready for that because this might happen more often than you expect.


** Creating a new card
:PROPERTIES:
:ID:       65FBC7A2-7F72-47E8-9462-58E35974DE1D
:END:

The front of the card has a link for the problem.  The back of the card has the steps to solve the problem and optionally an example for the solution.  You might get stuck trying to write the /perfect/ card.  Don't bother with this.  You will have many opportunities to improve them after a review session.


* FAQ

** When should I work in a new problem?

Don't start working in a new problem if you have more reviews than you have time to get them done in a day, or you already have new cards waiting for you.  It is easy to get overwhelmed with the number of reviews.  Striving for consistency will bring better results than rushing every other day.

** Should I code the solution on every review?

Yes!  Reconstructing your steps to the solution and writing the code again will cement the building blocks on your memory.

** What should I do if I can't solve a problem?

First of all, that is fine and will happen more frequently than you imagine.  Give at least one day before looking to solutions.  After you read and *understand* a solution, ask yourself "what steps should I have done to solve this problem?".  Create a card with these steps and review it as any other card.


* Meetings

** December 2, 2022

The goal of this method is to use spaced-repetition to build your intuition to solve coding challenges.  The card has the path to solve the problem and this will be internalized after many repetitions.  When solving new problems, a thought will scream at you "Binary Search!" or "This is a Graph Problem".  In fact, this is not much different of how we learned math.  How many times did you verbalize the steps to isolate $x$ in an equation?  You used descriptive knowledge to build the intuition muscle that later on helped you to perform simplification without using much mental energy.

For next session, you will work in [[https://leetcode.com/contest/weekly-contest-320/][4 problems]] which you should apply the method: solve them, create and review the cards.  We will review your thought process to solve these problems and what worked and didn't work when create and reviewing your cards:

  - [X] [[id:AD689352-C66F-4BFC-95A4-65B58110A851][Leetcode: 2475. Number of Unequal Triplets in Array]]
  - [X] [[id:7F2BA5B5-2C29-40AE-A4D3-B3D438A660C9][Leetcode: 2476. Closest Nodes Queries in a Binary Search Tree]]
  - [X] [[id:47D88994-CD09-41C5-A3BA-9EDF2B9AB80E][Leetcode: 2477. Minimum Fuel Cost to Report to the Capital]]
  - [ ] [[id:D500C3CF-B17C-4C7D-90F2-BFA02AB1C9D6][Leetcode: 2478. Number of Beautiful Partitions]]

** December 9, 2022

*** Performing a solution

- Found the worst case but didn't narrow the search for the optimal algorithm to that case.
- Explain what are chucks and how to use them.
  - [[https://www.theroar.com.au/2016/12/19/ten-ways-get-cricket-including-youve-never-seen/][What are the ways to be dismissed in cricket?]]
    - Define one of them.
    - Define other one.
    - Contrast them.
- Things that will improve over time:
  - Proficiency in the selected Programming Language.
  - Formulate a high-level plan and execute each part in isolation.

*** Problems

We will start with [[https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions][Blind 75]] problems.  As we work through them, we will find that few areas should get more attention.  For those, I will add problems to increase your proficiency on specific building blocks.  Here is the list of problems for this week:

- Blind 75:
  - [X] [[https://leetcode.com/problems/two-sum/][Two Sum]] ([[id:5F25DCD8-CE46-4F18-A1B1-952BC35382A9][solution]]).
  - [X] [[https://leetcode.com/problems/best-time-to-buy-and-sell-stock/][Best Time to Buy and Sell Stock]] ([[id:81682CDD-4D5A-485C-9C1C-5689B6AF1A41][solution]]).
  - [X] [[https://leetcode.com/problems/contains-duplicate/][Contains Duplicate]] ([[id:2E185F52-087B-4CBC-B927-1DD24C880E04][solution]] *NEW!*).
- Supplement:
  - [X] [[https://leetcode.com/problems/binary-tree-inorder-traversal/][Binary Tree Inorder Traversal]].

** December 14, 2022

*** Review last week's problems

- Done well.

  - Read the problem and checked the problem's constraints.

  - Used the problem constraints to define an upper bound for the solution's time complexity.

- Things to improve:

  - You might think that easy problems are waste of time.  They are not.  Easy problems help you to solidify building blocks, become proficient in your chosen programming language, focus on recalling the patterns and prompts, and finally explain the problem in a concise way.  Leave to the spaced-repetition the task to decide which problem you have to review.  Over time, the easy problems will appear less frequently than the challenging ones.

  - You added "Convert list to set" as one pattern in your card.  A pattern is word or sentence that abstract the problem or part of it.  Here is some examples of patterns: "Binary Balance Tree", "Directed Graph", "String Search", "Searching in Array".  Note that they generalize the problem in terms that are easier to associate with.  We are going to upse these terms (or sentences) as hooks to grab ideas from previous problems that we solved.  You think "Directed Graph", and few seconds later "poof" you think "Are there cycles in this Graph?".

  - While we love functional programming, imperative programming is usually a better choice for problem solving.  It is possible to use immutable data structures, lambdas, maps, filters, and etc, but a simple for loop can reduce 10-15 lines of functional programming to 3 lines.  Remember that less code means less surface for errors.

- Questions about the training:

  - Are you doing at least one/two reviews per day?
    - Every two days.
  - Is the number of reviews sustainable?
    - Yes. Problems are small and there is no issue so far.
  - Have you had chance to look the solutions available here?
    - Yes, but didn't understand part of the solution.
  - What insight did you extract after using this method in the last two weeks?
    - Solution for the past problems come to mind after much effort and don't require paper work before start coding.

- Questions about the problems:

  - What is common in the solution for these problems?  We have to use extra memory to solve the searching problem in $O(1)$.  In [[id:AF49B2EA-A026-4E91-A4EC-423123E63A9B][Improve Performance Using More Memory]], I argued why sometimes this is the case for improving performance.

*** Next problems

- [X] [[https://leetcode.com/problems/product-of-array-except-self/][Product of Array Except Self]] ([[id:489C947E-AD8A-4611-B8F7-DD0BB44ABAE5][solution]])
- [X] [[https://leetcode.com/problems/maximum-subarray/][Maximum Subarray]] ([[id:01AB9AC6-5E8D-49BB-9533-92B7032CFDE3][solution]])
- [ ] [[https://leetcode.com/problems/maximum-product-subarray/][Maximum Product Subarray]] ([[id:D821DCA2-8A6A-4650-BD9E-D9B78F446901][solution]])
- [X] [[https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/][Find Minimum in Rotated Sorted Array]] ([[id:C1F8B8F2-72CF-4085-852C-4D1EF8E19195][solution]])

** December 30, 2022

- Review of a card
  - [[https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/][Find Minimum in Rotated Sorted Array]]
    - Wrote the patterns and prompts as comments in the code.
      - It has can make easier to compare with the card and assess the review.
      - It makes easier to direct focus.
    - Implemented his solution and than the alternative one.
      - The familiarity with the language is noticeable.  Good job!
      - It is fine to breakdown the problem in smaller sub problems.
      - There is no problem with writing the recursive version of binary search, but the interviewer will ask you to save memory (stack) by having the iterative version.
      - Is there something that is blocking you to get to the alternative solution from the begin?
      - What is the difference between both approaches?

- As I mentioned before, I developed this method after 9 years without working on problem solving.  This is an example of how I improved by following this method:  [[https://leetcode.com/problems/maximum-subarray/submissions/541620453/][old solution]] from Aug 2021 vs [[https://leetcode.com/problems/maximum-subarray/submissions/860511074/][new solution]] from December 2022.  I knew that this is a classical problem, but I didn't remember that I solved it on Leetcode.  The new solution is shorter and straight to the point, while the old one is unnecessarily complex.


*** Next problems

- [X] [[https://leetcode.com/problems/search-in-rotated-sorted-array/][Search in Rotated Sorted Array]] ([[id:DE8C7F14-D36F-43BF-8AF1-B6940406EBF6][solution]] *NEW!*)
- [X] [[https://leetcode.com/problems/3sum/][3 Sum]] ([[id:F46A0FDA-FF12-42FF-8BA1-FEAC7D9B6A4B][solution]] *NEW!*)
- [X] [[https://leetcode.com/problems/container-with-most-water/][Container With Most Water]] ([[id:2EA371C3-FF87-4506-BE17-1AA2BDF0AB42][solution]] *NEW!*)
- [X] [[https://leetcode.com/problems/sum-of-two-integers/][Sum of Two Integers]]
- [X] [[https://leetcode.com/problems/number-of-1-bits/][Number of 1 Bits]] ([[id:9C506DBD-693B-46D8-9CA4-8B7C7D573092][solution]] *NEW!*)
- [X] [[https://leetcode.com/problems/counting-bits/][Counting Bits]] ([[id:BEB1C18C-3B4F-4805-913A-6E3EF9573515][solution]] *NEW!*)
- [X] [[https://leetcode.com/problems/missing-number/][Missing Number]] ([[id:A3920C94-A219-445F-987A-E2A08FFE8C46][solution]] *NEW!*)
- [X] [[https://leetcode.com/problems/reverse-bits/][Reverse Bits]]
- [X] [[https://leetcode.com/problems/climbing-stairs/][Climbing Stairs]]
- [X] [[https://leetcode.com/problems/coin-change/][Coin Change]]
- [X] [[https://leetcode.com/problems/longest-increasing-subsequence/][Longest Increasing Subsequence]]
- [X] [[https://leetcode.com/problems/longest-common-subsequence/][Longest Common Subsequence]]
- [X] [[https://leetcode.com/problems/word-break/][Word Break Problem]]
- [X] [[https://leetcode.com/problems/combination-sum-iv/][Combination Sum]]
- [X] [[https://leetcode.com/problems/house-robber/][House Robber]]
- [X] [[https://leetcode.com/problems/house-robber-ii/][House Robber II]]
- [X] [[https://leetcode.com/problems/decode-ways/][Decode Ways]]
- [X] [[https://leetcode.com/problems/jump-game/][Jump Game]]
- [X] [[https://leetcode.com/problems/insert-interval/][Insert Interval]]
- [X] [[https://leetcode.com/problems/merge-intervals/][Merge Intervals]]

** February 3, 2023

- Question from V :: How do you organize your knowledge about algorithms and techniques?

  - Years ago, it was allowed to bring a booklet as reference material to competition.  So, I had my booklet with important algorithms and ideas that I judged useful to bring to the competitions.  I didn't include simple algorithms like DFS or BFS, but ones that are hard or trickier to write.  For interview preparation, this is not required since you will end up training frequent problems that appear on interviews and they won't use complex algorithms or ideas.  Besides that, there is a human need to organize knowledge into hierarchies.  You shouldn't fall in this trap.  Let the problems tell what topic you have to master, and let the space repetition decide what material you have to master or not.

- Question from V :: Should we study algorithms or techniques in isolation?

  - I don't think that it is necessary.  The review process takes care of exercising all components of the problem solving skill: extract the patterns from the text, recall algorithms/techniques/ideas using the patterns, adapting previous knowledge to the problem and implementing it.  If you focus to execute every single step to the perfection, you will not only sharp your algorithms and techniques but the necessary connections to apply them in practice.

*** Next problems

- [ ] [[https://leetcode.com/problems/unique-paths/][Unique Paths]]
- [ ] [[https://leetcode.com/problems/clone-graph/][Clone Graph]]
- [ ] [[https://leetcode.com/problems/course-schedule/][Course Schedule]]
- [ ] [[https://leetcode.com/problems/pacific-atlantic-water-flow/][Pacific Atlantic Water Flow]]
- [ ] [[https://leetcode.com/problems/number-of-islands/][Number of Islands]]
- [ ] [[https://leetcode.com/problems/longest-consecutive-sequence/][Longest Consecutive Sequence]]
- [ ] [[https://leetcode.com/problems/alien-dictionary/][Alien Dictionary (Leetcode Premium)]]
- [ ] [[https://leetcode.com/problems/graph-valid-tree/][Graph Valid Tree (Leetcode Premium)]]
- [ ] [[https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/][Number of Connected Components in an Undirected Graph (Leetcode Premium)]]
- [ ] [[https://leetcode.com/problems/non-overlapping-intervals/][Non-overlapping Intervals]]
- [ ] [[https://leetcode.com/problems/meeting-rooms/][Meeting Rooms (Leetcode Premium)]]
- [ ] [[https://leetcode.com/problems/meeting-rooms-ii/][Meeting Rooms II (Leetcode Premium)]]
- Extra:
  - [ ] [[https://leetcode.com/problems/find-peak-element/][Find Peak Element]] ([[id:E4E1316F-92A3-4C51-8FC6-16A39DD1C1CE][solution]])
  - [ ] [[https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/][Two Sum II - Input Array Is Sorted]] ([[id:1C65AE58-2344-4F0A-A336-77E587E81033][solution]] *NEW!*)

** February 10, 2023

In this meeting, we discussed the challenges of understanding problems before solving them.  We asked questions like what is our state of mind before and after we understand something?  Why is it so difficult to hold the urge to start solving the problem while we are reading it?  What can we use to improve our reading skills?  We discovered that by using active reading techniques, we can enhance our understanding of problems and improve our ability to solve them.

Let's start with an experiment:

- Take a problem statement or a paragraph from a book that you never read before.
- Read it as you normally read.
- Close the book or switch to other tab in your browser and explain what you've read.
- Do it again 3 to 5 times.

You will find that the recall became better and better with each repetition.  The first recall was disorganized and the last one was organized and fluid, like a story.  You might have tried to see part of the page with your mind's eye on the first recall.  But gradually, it became unnecessary as the chain of thoughts formed after each repetition.  You started empty and finished with a piece of knowledge inside yourself.

What did you feel on each repetition and how did it change over time?  I bet that recognizing this difference can help us understand when we should spend more time to really understand something.  I asked four people to do this experiment and to report what they felt.  The answers were essentially about becoming less anxious and disorganized and more calm and organized.  And this is the clue that we can use.

Our reading skills have everything to do with our problem solving skills.  As stated in the famous book "[[https://en.wikipedia.org/wiki/How_to_Solve_It][How To Solve It by George Polya]]", the first step of solving a problem is understating it.  To understand the problem, we have to read it.  And let's be honest,  we usually read the problem once and try to solve it as we go along.

We tried to address the issue using active reading techniques.  Here is the process that we followed:

  1. Read the problem quickly to get an overall idea.
  2. Read the problem in normal speed to discover important parts.
  3. Take a break and focus on the next 10 breathes (yep! like in meditation).
  4. Read the problem slowly to ensure full understand.

After each step, ask yourself "What is this problem about?".  V and I tested this method in Leetcode problems and found an impressive improvement in recall quality.  The difference was "night and day".

In conclusion, I will incorporate active reading in my training routine and will report back the results in the future.


* Blind 75 :noexport:

- Array
  - [[https://leetcode.com/problems/two-sum/][Two Sum]]
  - [[https://leetcode.com/problems/best-time-to-buy-and-sell-stock/][Best Time to Buy and Sell Stock]]
  - [[https://leetcode.com/problems/contains-duplicate/][Contains Duplicate]]
  - [[https://leetcode.com/problems/product-of-array-except-self/][Product of Array Except Self]]
  - [[https://leetcode.com/problems/maximum-subarray/][Maximum Subarray]]
  - [[https://leetcode.com/problems/maximum-product-subarray/][Maximum Product Subarray]]
  - [[https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/][Find Minimum in Rotated Sorted Array]]
  - [[https://leetcode.com/problems/search-in-rotated-sorted-array/][Search in Rotated Sorted Array]]
  - [[https://leetcode.com/problems/3sum/][3 Sum]]
  - [[https://leetcode.com/problems/container-with-most-water/][Container With Most Water]]
- Binary
  - [[https://leetcode.com/problems/sum-of-two-integers/][Sum of Two Integers]]
  - [[https://leetcode.com/problems/number-of-1-bits/][Number of 1 Bits]]
  - [[https://leetcode.com/problems/counting-bits/][Counting Bits]]
  - [[https://leetcode.com/problems/missing-number/][Missing Number]]
  - [[https://leetcode.com/problems/reverse-bits/][Reverse Bits]]
- Dynamic Programming
  - [[https://leetcode.com/problems/climbing-stairs/][Climbing Stairs]]
  - [[https://leetcode.com/problems/coin-change/][Coin Change]]
  - [[https://leetcode.com/problems/longest-increasing-subsequence/][Longest Increasing Subsequence]]
  - [[https://leetcode.com/problems/longest-common-subsequence/][Longest Common Subsequence]]
  - [[https://leetcode.com/problems/word-break/][Word Break Problem]]
  - [[https://leetcode.com/problems/combination-sum-iv/][Combination Sum]]
  - [[https://leetcode.com/problems/house-robber/][House Robber]]
  - [[https://leetcode.com/problems/house-robber-ii/][House Robber II]]
  - [[https://leetcode.com/problems/decode-ways/][Decode Ways]]
  - [[https://leetcode.com/problems/unique-paths/][Unique Paths]]
  - [[https://leetcode.com/problems/jump-game/][Jump Game]]
- Graph
  - [[https://leetcode.com/problems/clone-graph/][Clone Graph]]
  - [[https://leetcode.com/problems/course-schedule/][Course Schedule]]
  - [[https://leetcode.com/problems/pacific-atlantic-water-flow/][Pacific Atlantic Water Flow]]
  - [[https://leetcode.com/problems/number-of-islands/][Number of Islands]]
  - [[https://leetcode.com/problems/longest-consecutive-sequence/][Longest Consecutive Sequence]]
  - [[https://leetcode.com/problems/alien-dictionary/][Alien Dictionary (Leetcode Premium)]]
  - [[https://leetcode.com/problems/graph-valid-tree/][Graph Valid Tree (Leetcode Premium)]]
  - [[https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/][Number of Connected Components in an Undirected Graph (Leetcode Premium)]]
- Interval
  - [[https://leetcode.com/problems/insert-interval/][Insert Interval]]
  - [[https://leetcode.com/problems/merge-intervals/][Merge Intervals]]
  - [[https://leetcode.com/problems/non-overlapping-intervals/][Non-overlapping Intervals]]
  - [[https://leetcode.com/problems/meeting-rooms/][Meeting Rooms (Leetcode Premium)]]
  - [[https://leetcode.com/problems/meeting-rooms-ii/][Meeting Rooms II (Leetcode Premium)]]
- Linked List
  - [[https://leetcode.com/problems/reverse-linked-list/][Reverse a Linked List]]
  - [[https://leetcode.com/problems/linked-list-cycle/][Detect Cycle in a Linked List]]
  - [[https://leetcode.com/problems/merge-two-sorted-lists/][Merge Two Sorted Lists]]
  - [[https://leetcode.com/problems/merge-k-sorted-lists/][Merge K Sorted Lists]]
  - [[https://leetcode.com/problems/remove-nth-node-from-end-of-list/][Remove Nth Node From End Of List]]
  - [[https://leetcode.com/problems/reorder-list/][Reorder List]]
- Matrix
  - [[https://leetcode.com/problems/set-matrix-zeroes/][Set Matrix Zeroes]]
  - [[https://leetcode.com/problems/spiral-matrix/][Spiral Matrix]]
  - [[https://leetcode.com/problems/rotate-image/][Rotate Image]]
  - [[https://leetcode.com/problems/word-search/][Word Search]]
- String
  - [[https://leetcode.com/problems/longest-substring-without-repeating-characters/][Longest Substring Without Repeating Characters]]
  - [[https://leetcode.com/problems/longest-repeating-character-replacement/][Longest Repeating Character Replacement]]
  - [[https://leetcode.com/problems/minimum-window-substring/][Minimum Window Substring]]
  - [[https://leetcode.com/problems/valid-anagram/][Valid Anagram]]
  - [[https://leetcode.com/problems/group-anagrams/][Group Anagrams]]
  - [[https://leetcode.com/problems/valid-parentheses/][Valid Parentheses]]
  - [[https://leetcode.com/problems/valid-palindrome/][Valid Palindrome]]
  - [[https://leetcode.com/problems/longest-palindromic-substring/][Longest Palindromic Substring]]
  - [[https://leetcode.com/problems/palindromic-substrings/][Palindromic Substrings]]
  - [[https://leetcode.com/problems/encode-and-decode-strings/][Encode and Decode Strings (Leetcode Premium)]]
- Tree
  - [[https://leetcode.com/problems/maximum-depth-of-binary-tree/][Maximum Depth of Binary Tree]]
  - [[https://leetcode.com/problems/same-tree/][Same Tree]]
  - [[https://leetcode.com/problems/invert-binary-tree/][Invert/Flip Binary Tree]]
  - [[https://leetcode.com/problems/binary-tree-maximum-path-sum/][Binary Tree Maximum Path Sum]]
  - [[https://leetcode.com/problems/binary-tree-level-order-traversal/][Binary Tree Level Order Traversal]]
  - [[https://leetcode.com/problems/serialize-and-deserialize-binary-tree/][Serialize and Deserialize Binary Tree]]
  - [[https://leetcode.com/problems/subtree-of-another-tree/][Subtree of Another Tree]]
  - [[https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/][Construct Binary Tree from Preorder and Inorder Traversal]]
  - [[https://leetcode.com/problems/validate-binary-search-tree/][Validate Binary Search Tree]]
  - [[https://leetcode.com/problems/kth-smallest-element-in-a-bst/][Kth Smallest Element in a BST]]
  - [[https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/][Lowest Common Ancestor of BST]]
  - [[https://leetcode.com/problems/implement-trie-prefix-tree/][Implement Trie (Prefix Tree)]]
  - [[https://leetcode.com/problems/add-and-search-word-data-structure-design/][Add and Search Word]]
  - [[https://leetcode.com/problems/word-search-ii/][Word Search II]]
- Heap
  - [[https://leetcode.com/problems/merge-k-sorted-lists/][Merge K Sorted Lists]]
  - [[https://leetcode.com/problems/top-k-frequent-elements/][Top K Frequent Elements]]
  - [[https://leetcode.com/problems/find-median-from-data-stream/][Find Median from Data Stream]]
